//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IT_Comp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int eno { get; set; }
        public string ename { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> byear { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string picture { get; set; }
        public Nullable<int> dno { get; set; }
    
        public virtual department department { get; set; }
    }
}
